/** @type {import('tailwindcss').Config} */
module.exports = {
  content: {
    files: ["./src/**/*.{js,jsx}"],
    safelist: [
      "bg-water",
      "bg-fire",
      "bg-grass",
      "bg-electric",
      "bg-psychic",
      "bg-ice",
      "bg-dragon",
      "bg-dark",
      "bg-fairy",
      "bg-normal",
      "bg-fighting",
      "bg-flying",
      "bg-poison",
      "bg-ground",
      "bg-rock",
      "bg-bug",
      "bg-ghost",
      "bg-steel",
    ],
  },
  theme: {
    extend: {
      fontFamily: {
        pokedex: ['"Roboto Condensed"', "Arial", "sans-serif"],
      },
      colors: {
        primary: "#E3350D",
        "primary-active": "#C12F0A",
        "secondary-1": "#F5AC78",
        "secondary-2": "#4E82B4",
        "main-bg": "#121212",
        "content-bg": "#1E1E1E",
        "font-primary": "#FFFFFF",
        "font-secondary": "#CCCCCC",
        success: "#388E3C",
        error: "#D32F2F",
        warning: "#FBC02D",
        info: "#1976D2",
        water: "#6890F0",
        fire: "#F08030",
        grass: "#78C850",
        electric: "#F8D030",
        psychic: "#F85888",
        ice: "#98D8D8",
        dragon: "#7038F8",
        dark: "#705848",
        fairy: "#EE99AC",
        normal: "#A8A878",
        fighting: "#C03028",
        flying: "#A890F0",
        poison: "#A040A0",
        ground: "#E0C068",
        rock: "#B8A038",
        bug: "#A8B820",
        ghost: "#705898",
        steel: "#B8B8D0",
      },
    },
  },
  plugins: [],
};
